// Generated by scripts/embed-migrations.ts — do not edit manually.
// Run "bun run embed:migrations" after adding new migrations.
import journalJson from "./migrations/meta/_journal.json" with { type: "json" };
import m0000 from "./migrations/0000_tidy_namor.sql" with { type: "text" };
import m0001 from "./migrations/0001_complete_starjammers.sql" with { type: "text" };
import m0002 from "./migrations/0002_sloppy_eternals.sql" with { type: "text" };

const files: Record<string, string> = {
  "0000_tidy_namor.sql": m0000,
  "0001_complete_starjammers.sql": m0001,
  "0002_sloppy_eternals.sql": m0002,
};

/** Embedded migration SQL keyed by filename, plus the raw journal JSON. */
export const embeddedMigrations = { journal: JSON.stringify(journalJson), files };

/** Number of migrations compiled into this binary. Zero means a packaging fault. */
export const embeddedMigrationCount: number = Object.keys(files).length;
