/**
 * Generates src/db/migrations-embedded.ts from the SQL files in src/db/migrations/.
 *
 * Run after every `drizzle-kit generate`:
 *   bun run embed:migrations
 *
 * The generated file imports each .sql file with `with { type: "text" }` so that
 * `bun build --compile` bundles the SQL directly into the binary — no migrations
 * folder needed at the install site.
 */

import { readdir } from "node:fs/promises";
import { join } from "node:path";

const MIGRATIONS_DIR = "./src/db/migrations";
const META_DIR = "./src/db/migrations/meta";
const JOURNAL_FILE = join(META_DIR, "_journal.json");
const OUTPUT_FILE = "./src/db/migrations-embedded.ts";

interface JournalEntry {
  idx: number;
  tag: string;
}

interface Journal {
  entries: JournalEntry[];
}

const journalText = await Bun.file(JOURNAL_FILE).text();
const journal = JSON.parse(journalText) as Journal;

if (journal.entries.length === 0) {
  console.error("✖ _journal.json lists no migrations — run drizzle-kit generate first");
  process.exit(1);
}

// Read all .sql files from the migrations dir (exclude subdirs)
const allFiles = (await readdir(MIGRATIONS_DIR, { withFileTypes: true }))
  .filter(d => d.isFile() && d.name.endsWith(".sql"))
  .map(d => d.name)
  .sort();

// Every journal entry must have a matching file
for (const entry of journal.entries) {
  const expected = `${entry.tag}.sql`;
  if (!allFiles.includes(expected)) {
    console.error(`✖ journal entry "${entry.tag}" has no matching file ${expected}`);
    process.exit(1);
  }
}

// No extra SQL files outside the journal
const journalFileNames = new Set(journal.entries.map(e => `${e.tag}.sql`));
for (const file of allFiles) {
  if (!journalFileNames.has(file)) {
    console.error(`✖ file "${file}" exists in migrations/ but is not listed in the journal`);
    process.exit(1);
  }
}

// Build the generated source
const importLines = journal.entries.map((entry, i) => {
  const varName = `m${String(i).padStart(4, "0")}`;
  return `import ${varName} from "./migrations/${entry.tag}.sql" with { type: "text" };`;
});

const fileEntries = journal.entries.map((entry, i) => {
  const varName = `m${String(i).padStart(4, "0")}`;
  return `  "${entry.tag}.sql": ${varName},`;
});

const generated = `\
// Generated by scripts/embed-migrations.ts — do not edit manually.
// Run "bun run embed:migrations" after adding new migrations.
import journalJson from "./migrations/meta/_journal.json" with { type: "json" };
${importLines.join("\n")}

const files: Record<string, string> = {
${fileEntries.join("\n")}
};

/** Embedded migration SQL keyed by filename, plus the raw journal JSON. */
export const embeddedMigrations = { journal: JSON.stringify(journalJson), files };

/** Number of migrations compiled into this binary. Zero means a packaging fault. */
export const embeddedMigrationCount: number = Object.keys(files).length;
`;

await Bun.write(OUTPUT_FILE, generated);
console.log(`✅ Embedded ${journal.entries.length} migration(s) → ${OUTPUT_FILE}`);
